name: LegislationLinksApp

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
        
    - name: Build and deploy the Docker image (server)
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          SERVER_APP_NAME: ${{ 'legislation-links-app-server' }}
          CLIENT_APP_NAME: ${{ 'legislation-links-app-client' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $SERVER_APP_NAME
        heroku container:release web -a $SERVER_APP_NAME
        cd client
        heroku container:push web -a $CLIENT_APP_NAME
        heroku container:release web -a $CLIENT_APP_NAME
